### ISSUE TITLE
Add `MoveToHeaderJwtBearerQueryStringBehavior` implementation

### ISSUE THREAD

**Issue by carusology** [invio/Invio.Extensions.Authentication.JwtBearer#7]
**Background**

As an alternative to ["redacting" tokens from query strings](https://github.com/invio/Invio.Extensions.Authentication.JwtBearer/blob/master/src/Invio.Extensions.Authentication.JwtBearer/RedactJwtBearerQueryStringBehavior.cs), we can also move tokens to [the `Authorization` HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization). This enables code downstream to assume the token is always present in the authorization header.

An interesting use case this enables is putting [the middleware](https://github.com/invio/Invio.Extensions.Authentication.JwtBearer/blob/master/src/Invio.Extensions.Authentication.JwtBearer/JwtBearerQueryStringMiddleware.cs) in front of any authentication code rather than mutating the authentication code to allow for query strings.

**Task**

 * [ ] Add a `MoveToHeaderJwtBearerQueryStringBehavior` implementation of [`IJwtBearerQueryStringBehavior`](https://github.com/invio/Invio.Extensions.Authentication.JwtBearer/blob/master/src/Invio.Extensions.Authentication.JwtBearer/IJwtBearerQueryStringBehavior.cs) that removes the token from the query string and puts it into [the `Authorization` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) using [the `Bearer` authentication scheme](https://tools.ietf.org/html/rfc6750).
* [ ] Update [`QueryStringBehaviors`](https://github.com/invio/Invio.Extensions.Authentication.JwtBearer/blob/master/src/Invio.Extensions.Authentication.JwtBearer/QueryStringBehaviors.cs) to have a new immutable `MoveToHeader` property that returns this behavior.
* [ ] Update [`README`](https://github.com/invio/Invio.Extensions.Authentication.JwtBearer/blob/master/README.md) to reference the fact that this behavior can be put in front of the authentication middleware.
